sudo: required
services:
    - docker

before_install:
    - docker build -t buttonsmashstudios/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true buttonsmashstudios/docker-react npm run test --coverage